# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Danland
email: dan@danlandonline.net
description: >- # this means to ignore newlines until "baseurl:"
  Attempting to create a new Danland experience
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danlandonline.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: false
  email: true

social:
  github: g0blue
  twitter: dj_g0blue
  rss: feed.xml


permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
hard_wrap: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - _posts.old

